name: MySQL
secrets:
  db_user:
    description: Root user to assign to the component's DB
    default: architect
  db_pass:
    description: Root password to assign to the component's DB
    default: secret
  db_name:
    description: Name of the DB the component will store content in
    default: api-db
  db_port:
    description: Port for the db
    default: 3306
services:
  api-db:
    image: mysql:latest
    interfaces:
      database:
        port: ${{ secrets.db_port }}
        username: ${{ secrets.db_user }}
        password: ${{ secrets.db_pass }}
        protocol: mysql
    environment:
      MYSQL_USER: ${{ secrets.db_user }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.db_pass }}
      MYSQL_PASSWORD: ${{ secrets.db_pass }}
      MYSQL_DATABASE: ${{ secrets.db_name }}
